// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCncJJ8meQ_AFjf_y4lOPYQQtm_jZlv1is',
    appId: '1:771483726869:android:2f93e563765bf606464a1c',
    messagingSenderId: '771483726869',
    projectId: 'new-project-48873',
    storageBucket: 'new-project-48873.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy-B8CArH70SqnUX73E5_7rdWFT_4CI7w',
    appId: '1:771483726869:ios:f095601ca2404f14464a1c',
    messagingSenderId: '771483726869',
    projectId: 'new-project-48873',
    storageBucket: 'new-project-48873.appspot.com',
    iosBundleId: 'com.example.fluttterTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg7ZyziYxSbKYtXbE_tBPpX7Z8XR7JZaE',
    appId: '1:771483726869:web:dffc9ffc8df5d248464a1c',
    messagingSenderId: '771483726869',
    projectId: 'new-project-48873',
    authDomain: 'new-project-48873.firebaseapp.com',
    storageBucket: 'new-project-48873.appspot.com',
    measurementId: 'G-DG7P25JMH5',
  );
}
